" olvior's vimrc

call plug#begin()

if !(expand("%:e") == "java")
    Plug 'sheerun/vim-polyglot'
endif

Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

" Plug 'liuchengxu/vim-clap'

call plug#end()


runtime config/settings.vim

runtime config/mappings.vim

runtime config/functions.vim

runtime config/autocomplete.vim

runtime config/autocommands.vim

runtime config/ui.vim



