" olvior's vimrc

call plug#begin()

if !(expand("%:e") == "java")
    Plug 'sheerun/vim-polyglot'
endif
" putting the default back
set directory=.,~/tmp,/var/tmp,/tmp

call plug#end()

runtime config/settings.vim

runtime config/mappings.vim

runtime config/functions.vim

runtime config/autocomplete.vim

runtime config/autocommands.vim

runtime config/ui.vim

